services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=true   # 重要！ホストの変更をコンテナで検知
    depends_on:
      - backend
    volumes:
      - ./frontend:/app          # ホストの変更を反映
      - /app/node_modules        # コンテナ内 node_modules を保持

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - VOICEVOX_URL=http://voicebox:50021
      - DB_PATH=/app/data/people.db
    depends_on:
      - voicebox
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    command: bash -lc "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  voicebox:
    image: voicevox/voicevox_engine:cpu-latest
    container_name: voicebox
    ports:
      - "50021:50021"
