version: "3.9"

services:
  frontend:
    image: node:20-slim
    container_name: frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: bash -lc "corepack enable && yarn install && yarn dev"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - VOICEVOX_URL=http://voicebox:50021
    depends_on:
      - voicebox
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
  voicebox:
    image: voicevox/voicevox_engine:cpu-latest
    container_name: voicebox
    ports:
      - "50021:50021"
